# Dependabot
version: 2
updates:
    # Maintain dependencies for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
    # Maintain dependencies for npm
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      ignore:
          - dependency-name: "*"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
