env:
    browser: true
    es2021: true
extends:
    - "eslint:recommended"
    - "plugin:react/recommended"
    - "plugin:jsx-a11y/recommended"
    - "plugin:react-hooks/recommended"
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
rules:
    {
        "jsx-a11y/anchor-is-valid": 0,
        "react/react-in-jsx-scope": 0,
        "react/prop-types": 0,
        "no-undef": 0,
    }
settings:
    linkComponents:
        - name: Link
          linkAttribute: href
